

# This file was *autogenerated* from the file sage_toric_analysis.sage
from sage.all_cmdline import *   # import sage library

_sage_const_60 = Integer(60); _sage_const_3 = Integer(3)
import json

# Load (36, 98) polytope from CYTools export
with open('/tmp/cy_36_98_data.json') as f:
    data = json.load(f)

verts = data['vertices']
print("=" * _sage_const_60 )
print("IDCM CY3 — SageMath TORIC ANALYSIS")
print("=" * _sage_const_60 )

# Create lattice polytope
LP = LatticePolytope(verts)
print(f"\nLattice Polytope (4D reflexive):")
print(f"  Dimension: {LP.dim()}")
print(f"  Vertices: {LP.nvertices()}")
print(f"  Points: {LP.npoints()}")
print(f"  Reflexive: {LP.is_reflexive()}")
print(f"  Facets: {LP.nfacets()}")

# Try nef partition computation
nef_parts = LP.nef_partitions()
print(f"\nNef partitions: {len(nef_parts)}")
if nef_parts:
    for i, np_ in enumerate(nef_parts[:_sage_const_3 ]):
        print(f"  #{i}: {np_}")

# Use CYTools via subprocess for Hodge numbers
import subprocess
result = subprocess.run([
    'python3', '-c', '''
from cytools import fetch_polytopes, config
config.enable_experimental_features()
p = list(fetch_polytopes(h11=36, h21=98, limit=1))[0]
tri = p.triangulate()
cy = tri.get_cy()
print(f"H11={cy.h11()} H21={cy.h21()} Chi={cy.chi()}")
print(f"Smooth={cy.is_smooth()}")
'''
], capture_output=True, text=True, env={"PATH": "/tmp/cy_venv/bin:$PATH"})
print(f"\nCYTools via Sage subprocess:")
print(f"  {result.stdout.strip().replace(chr(10), chr(10)+'  ')}")

# Try to use Sage's built-in PALP interface
print(f"\npoly.x output:")
print(f"  {LP.poly_x('S')}")  # Symmetry check

# Check dual polytope
DP = LP.dual()
print(f"\nDual Polytope:")
print(f"  Dimension: {DP.dim()}")
print(f"  Vertices: {DP.nvertices()}")
print(f"  Points: {DP.npoints()}")
print(f"  Reflexive: {DP.is_reflexive()}")

print(f"\n" + "=" * _sage_const_60 )
print("SageMath analysis complete!")
print("=" * _sage_const_60 )

