#!/usr/bin/env python3
"""Export CY₃(36,98) fan data from CYTools for cohomCalg"""
import json, sys
from pathlib import Path

DATA = Path("/home/wsl/IDCM/IDCM-Information-Dynamics-Cosmology-Model/data/cy_search/data")

# Load the full sage export for polytope points
with open(DATA / "cy36_98_sage_export.json") as f:
    poly_data = json.load(f)

# Load the triangulation/toric data
with open(DATA / "sagemath_phases234.json") as f:
    fan_data = json.load(f)

points = poly_data["points"]  # 48 points in 4D
n_rays = fan_data["n_rays_fan"]  # 37 rays
ambient_rank = fan_data["ambient_picard_rank"]  # 32
h11_cy = fan_data["h11_cy"]  # 36
extra = fan_data["extra_classes"]  # 3

print(f"Points: {len(points)}")
print(f"Fan rays: {n_rays}")
print(f"Ambient Picard rank: {ambient_rank}")
print(f"CY h^11: {h11_cy}")
print(f"Extra classes: {extra}")

# The points are the lattice points from the polytope
# The first 6 are vertices, the rest are interior points
# The resolved fan uses all points as rays

# For cohomCalg input, we need:
# 1. Up to 20 vertices (cohomcalg limit for practical computation)
# 2. GLSM charges for each
# 3. SR ideal from triangulation

# The 6-vertex fan gives us the unresolved toric variety
# The resolved fan (48 rays) is too large for cohomcalg

# Strategy: compute ambient cohomology on the unresolved (6-vertex) fan
# which should still give the correct CY cohomology via Koszul LES
# since the CY hypersurface is in the anticanonical class

# Write out the 6-vertex fan input
print("\nWriting 6-vertex cohomCalg input...")
vertices = poly_data["vertices"]  # 6 vertices in 4D

# Get GLSM charges from final data
with open(DATA / "cy36_98_final.json") as f:
    final = json.load(f)
glsm = final["glsm_coord3"]  # 32 charges

# Map: the 6 vertices correspond to the first 6 entries of glsm
# (this is the standard CYTools ordering)
coords_4d = [v[:4] for v in vertices]  # 4D coordinates

lines = [
    "# cohomCalg input for CY₃(36,98) — 6-vertex unresolved fan",
    f"# Polytope: {len(vertices)} vertices, 4D reflexive",
    "# GLSM charges from coord3",
    ""
]

for i, (coord, q) in enumerate(zip(vertices, glsm[:6])):
    coord_str = ", ".join(str(c) for c in coord[:4])
    pic_label = f"PIC: D{i}" if i == 0 else ""
    lines.append(f"vertex v{i} = ( {coord_str} ) | {pic_label} GLSM: ( {int(q)} );")

# SR ideal: for a 4D polytope with 6 vertices,
# the SR ideal is generated by triples that don't form a cone
# For a projective fan, the minimal SR relations are:
# All vertices together: v0*v1*v2*v3*v4*v5 is the maximal product
# Subsets that form cones are allowed
# For a simplicial fan, the minimal SR generators are complements of cones

# For the 6-vertex fan of this polytope:
# Each cone has dimension 4, so needs 4 independent rays
# The SR ideal forbids sets of vertices that don't form a face
# The face fan has all 6-choose-4 = 15 possible 4-vertex cones
# The missing ones correspond to the SR generators

# For a generic 4D polytope with 6 vertices, the SR ideal
# is generated by the products of vertices that are NOT in any cone face
# Each cone is 4D, so each SR generator is the product of 2 vertices

# From the sage analysis, the fan is complete and smooth
# We'll use the full product as SR generator for simplicity
sr_terms = ["v0", "v1", "v2", "v3", "v4", "v5"]
lines.append(f"srideal [{'*'.join(sr_terms)}];")
lines.append("")

# Ambient cohomology requests
# O(D_i) for each vertex divisor (these are the 6 basic line bundles)
for i in range(6):
    charge_str = " ".join("1" if j == i else "0" for j in range(6))
    lines.append(f"ambientcohom O( {charge_str} );")

# Anti-canonical (the CY hypersurface)
lines.append(f"ambientcohom O( -1 -1 -1 -1 -1 -1 );")
lines.append("")

output = "\n".join(lines)
outpath = Path("/home/wsl/IDCM/cohomcalg_cy36_98.in")
outpath.write_text(output)
print(f"Wrote {len(lines)} lines to {outpath}")
print("\nFirst 10 lines:")
for line in lines[:10]:
    print(f"  {line}")
