"""
FINAL: 36D TRIPLE INTERSECTION TENSOR κ_ijk
=============================================
Compute ALL 8436 triple intersection entries in SageMath's
Chow ring (which already handles the 475 SR generators).
"""


# This file was *autogenerated* from the file idcm_kappa_36d.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_16 = Integer(16); _sage_const_3 = Integer(3); _sage_const_70 = Integer(70); _sage_const_37 = Integer(37); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_0p090141 = RealNumber('0.090141'); _sage_const_0p0 = RealNumber('0.0'); _sage_const_6p0 = RealNumber('6.0'); _sage_const_12 = Integer(12); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_2p0 = RealNumber('2.0')
import os, json, math, sys, time
from sage.all import *
from sage.schemes.toric.all import *
from sage.geometry.cone import *

DATA_DIR = "/home/wsl/IDCM/IDCM-Information-Dynamics-Cosmology-Model/data/cy_search/data"
with open(os.path.join(DATA_DIR, "cy36_98_sage_export.json")) as f:
    data = json.load(f)
pts = data["points"]; simps = data["simplices"]

PHI = (_sage_const_1 +math.sqrt(_sage_const_5 ))/_sage_const_2 ; PHI_INV = PHI-_sage_const_1 ; LN_PHI = math.log(PHI)
BETA = PHI_INV/_sage_const_2 ; KAPPA3 = (_sage_const_1 /_sage_const_16 )**_sage_const_3 

print("="*_sage_const_70 )
print("FINAL 36D TRIPLE INTERSECTION TENSOR")
print("="*_sage_const_70 )

# Simplicial fan (36 non-origin rays, 4 rays per cone)
fan_pts = [vector(ZZ, pts[i]) for i in range(_sage_const_37 )]
cones = [[i for i in s if i != _sage_const_0 ] for s in simps if len([i for i in s if i != _sage_const_0 ]) == _sage_const_4 ]
F = Fan(cones, fan_pts, lattice=ToricLattice(_sage_const_4 ), check=True)
X = ToricVariety(F)
H = X.cohomology_ring()
D = [H(d) for d in X.toric_divisor_group().gens()]
nD = len(D)
antiK = H(-X.K())
print(f"  {nD} divisors, cohomology ring ready")

# ============================================================
# FULL TRIPLE INTERSECTION
# ============================================================
print(f"\n  Computing κ_ijk = ∫ D_i·D_j·D_k·(-K_X) for all {nD} divisors...")
print(f"  Total symmetric entries: {nD*(nD+1)*(nD+2)//6}\n")

kappa = {}
count = _sage_const_0 ; nonzero = _sage_const_0 
t0 = time.time()
for i in range(nD):
    for j in range(i, nD):
        for k in range(j, nD):
            prod = D[i] * D[j] * D[k] * antiK
            val = X.integrate(prod)
            key = f"{i},{j},{k}"
            kappa[key] = int(val) if val else _sage_const_0 
            count += _sage_const_1 
            if val:
                nonzero += _sage_const_1 
    if (i+_sage_const_1 ) % _sage_const_6  == _sage_const_0  or i == nD-_sage_const_1 :
        elapsed = time.time() - t0
        rate = count / elapsed if elapsed > _sage_const_0  else _sage_const_0 
        print(f"    [{i+1:2d}/{nD}] {count} entries, {nonzero} non-zero, "
              f"{elapsed:.0f}s @ {rate:.0f}/s")

print(f"\n  Done: {count} entries, {nonzero} non-zero")
print(f"  Sparsity: {(1-nonzero/count)*100:.1f}% zero")

# ============================================================
# EXTRACT FN CHARGES AT J*
# ============================================================
print(f"\n  Computing volume functional and J* FN charges...")
# The volume functional: Vol(t) = (1/6) Σ κ_ijk t_i t_j t_k
# At J* with uniform scaling t_i = scale:
scale = _sage_const_0p090141 

# Build the symmetric kappa matrix
kappa_mat = [[[_sage_const_0 ]*nD for _ in range(nD)] for __ in range(nD)]
for key, val in kappa.items():
    i, j, k = [int(x) for x in key.split(",")]
    val_int = int(val) if val else _sage_const_0 
    for (a,b,c) in [(i,j,k), (i,k,j), (j,i,k), (j,k,i), (k,i,j), (k,j,i)]:
        kappa_mat[a][b][c] = val_int

# Volume at any t
def vol_t(t):
    s = _sage_const_0p0 
    for i in range(nD):
        for j in range(i, nD):
            for k in range(j, nD):
                s += kappa_mat[i][j][k] * t[i] * t[j] * t[k]
    return s / _sage_const_6p0 

# Check uniform J*
t_uniform = [scale] * nD
v_uniform = vol_t(t_uniform)
print(f"\n  Uniform J*: Vol = {v_uniform:.6e} (target {KAPPA3:.6e})")

# GLSM charges
glsm = data["glsm_matrix"]
glsm_c3 = [int(glsm[i,_sage_const_3 ]) for i in range(min(glsm.shape[_sage_const_0 ], nD))]
charge_rays = {c: [i for i,r in enumerate(glsm_c3) if r==c] for c in [_sage_const_12 ,_sage_const_10 ,_sage_const_9 ,_sage_const_8 ,_sage_const_7 ,_sage_const_6 ]}

print(f"\n  FN charges at uniform J*:")
for c, rays in charge_rays.items():
    if not rays: continue
    for r in rays:
        # ∂Vol/∂t_i = (1/2) Σ κ_ijk t_j t_k
        dvol = _sage_const_0p0 
        for j in range(nD):
            for k in range(j, nD):
                dvol += kappa_mat[r][j][k] * t_uniform[j] * t_uniform[k]
        dvol /= _sage_const_2p0 
        # k = -ln(Vol(D_i)/Vol(CY)) / ln(φ)  
        vol_div = dvol  # This is the divisor volume (not normalized)
        k_fn = -math.log(vol_div / v_uniform) / LN_PHI if vol_div > _sage_const_0  else _sage_const_0 
        print(f"    charge {c:2d} ray {r:2d}: Vol(D)={vol_div:.6e}, k={k_fn:.2f}")

print(f"\n{'='*70}")
print(f"36D TRIPLE INTERSECTION COMPLETE: {count} entries")
print(f"{'='*70}")

# Save
fpath = os.path.join(DATA_DIR, "kappa_36d_full.json")
with open(fpath, "w") as f:
    json.dump({"kappa": {k: int(v) for k,v in kappa.items() if v},
               "shape": [nD, nD, nD]}, f)
print(f"\nSaved to {fpath}")

